import type { Metadata } from "next";
import "./globals.css";

// redux store taunk
import Providers from "@/redux/Providers";
// import { store } from "@/redux/store";

// auto reload the app
import AppInit from "./AppInit";

// import components
import Navbar from "@/components/header/Navbar";
import Footer from "@/components/footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        {/* redux store provider */}
        <Providers>

          {/* auro reload the appinit */}
          <AppInit>


           
        {/* Navbar (global) */}
        <Navbar />

        {/* Main content (replacement for Outlet) */}
        <main className="mx-auto px-auto"> 
          {children}
        </main>

        {/* Footer (global) */}
        <Footer />

         </AppInit>

        </Providers>
      </body>
    </html>
  );
}
