// global.tailwind.css
import "./globals.css";

//  react-redux 
import Providers from "@/redux/Providers";

// import components
import Navbar from "@/components/header/Navbar";
import Footer from "@/components/footer/Footer";

// import toaster notificatiion
import { Toaster } from "@/components/ui/sonner";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>

        {/* redux store provider */}
        <Providers>

      

        {/* Navbar (global) */}
        <Navbar />

        {/* Main content (replacement for Outlet) */}
        <main className="mx-auto px-auto"> 
          {children}
        </main>

        <Toaster position="top-right" /> {/* render toast notifications */}

        {/* Footer (global) */}
        <Footer />

        </Providers>
      </body>
    </html>
  );
}
