//"use client"; // <--- Add this if this layout will host client pages like verify-otp
import type { Metadata } from "next";
import { Playfair_Display, Inter } from "next/font/google";
import "./globals.css";

// redux store taunk
import Providers from "@/redux/Providers";
// import { store } from "@/redux/store";

// import components
import Navbar from "@/components/header/Navbar";
import Footer from "@/components/footer/Footer";
import { Toaster } from "sonner";

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${playfair.variable} ${inter.variable}`}>
      <body className="antialiased min-h-screen bg-background text-foreground font-sans">

        {/* redux store provider */}
        <Providers>
           
        {/* Navbar (global) */}
        <Navbar />

        {/* Main content (replacement for Outlet) */}
        <main className="mx-auto px-auto"> 
          {children}
        </main>

        {/* Footer (global) */}
        <Footer />

        <Toaster position="top-right" richColors />

        </Providers>
      </body>
    </html>
  );
}
